list-component added
buzzsquez/rick-and-morty pull request #1
Opened 2022-11-02 15:20 UTC by buzzsquez

2022-11-02 16:10 UTC, NikitaPFE requested changes

2022-11-02 16:10 UTC, NikitaPFE commented on src/App.js
> +        <Route path="/characterList" element={<CharacterList />} />
dont use camelcase in url
character
character/:id

2022-11-02 16:10 UTC, NikitaPFE commented on src/pages/CharacterDetails/CharacterDetails.jsx
> +      });
dont forget about catch

2022-11-02 16:10 UTC, NikitaPFE commented on src/pages/CharacterList/CharacterList.jsx
> +        <button
use link instead of button

2022-11-03 11:28 UTC, buzzsquez reviewed
Fixed the code.

2022-11-03 11:28 UTC, buzzsquez commented on src/pages/CharacterDetails/CharacterDetails.jsx
> +      });
Got it! 
Done!

2022-11-05 07:32 UTC, NikitaPFE approved these changes

2022-11-05 07:32 UTC, merged